import { defineRailway, github, postgres, preserve, project, redis, service, volume } from "railway/iac";

export default defineRailway(() => {
  const tgshop = github("PubgmHacker/tgshop", { checkSuites: false });

  const Postgres = postgres("Postgres", { region: "sfo" });
  const Redis = redis("Redis", { region: "sfo" });
  Redis.deploy = { startCommand: "/bin/sh -c \"rm -rf $RAILWAY_VOLUME_MOUNT_PATH/lost+found/ && exec docker-entrypoint.sh redis-server --requirepass $REDIS_PASSWORD --save 60 1 --dir $RAILWAY_VOLUME_MOUNT_PATH\"" };
  const redisVolume = volume("redis-volume", { alerts: { usage: { "100": {}, "80": {}, "95": {} } }, allowOnlineResize: true, region: "sfo", sizeMB: 50000 });
  const postgresVolume = volume("postgres-volume", { alerts: { usage: { "100": {}, "80": {}, "95": {} } }, allowOnlineResize: true, region: "sfo", sizeMB: 50000 });
  const worker = service("worker", {
    source: tgshop,
    replicas: { "sfo": 1 },
    build: { watchPatterns: ["apps/worker/**", "packages/**", "package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "tsconfig.base.json"] },
    // Railway probes healthchecks on PORT; the worker's health server listens
    // on WORKER_HEALTH_PORT (default 3100), so PORT below points Railway there.
    healthcheck: "/health",
    healthcheckTimeout: 120,
    env: {
      ADMIN_IDS: preserve(),
      PORT: "3100",
      ADMIN_MINIAPP_URL: preserve(),
      ADMIN_URL: preserve(),
      BOT_TOKEN: preserve(),
      BOT_USERNAME: preserve(),
      CRYPTOBOT_API_TOKEN: preserve(),
      CRYPTOBOT_NETWORK: preserve(),
      CRYPTOBOT_WEBHOOK_SECRET: preserve(),
      DATABASE_URL: preserve(),
      ENCRYPTION_KEY: preserve(),
      JWT_SECRET: preserve(),
      LANDING_URL: preserve(),
      LOG_LEVEL: preserve(),
      MINIAPP_URL: preserve(),
      NEXT_PUBLIC_API_URL: preserve(),
      NEXT_PUBLIC_BOT_USERNAME: preserve(),
      PRICE_ORACLE_URL: preserve(),
      RAILWAY_DOCKERFILE_PATH: preserve(),
      REDIS_URL: preserve(),
      SERVICE_TOKEN: preserve(),
      SESSION_SECRET: preserve(),
      STARS_USD_RATE: preserve(),
      TRONGRID_API_KEY: preserve(),
      TRON_HOT_WALLET_KEY: preserve(),
      TRON_MASTER_XPUB: preserve(),
      TRON_MIN_CONFIRMATIONS: preserve(),
      TRON_NETWORK: preserve(),
      TRON_SWEEP_THRESHOLD: preserve(),
      TRON_SWEEP_TO_ADDRESS: preserve(),
      TRON_USDT_CONTRACT: preserve(),
      WEBHOOK_SECRET: preserve(),
      WEBHOOK_URL: preserve(),
    },
  });
  const landing = service("landing", {
    source: tgshop,
    replicas: { "sfo": 1 },
    build: { watchPatterns: ["apps/landing/**", "packages/**", "package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "tsconfig.base.json"] },
    healthcheck: "/",
    healthcheckTimeout: 120,
    env: {
      ADMIN_IDS: preserve(),
      ADMIN_MINIAPP_URL: preserve(),
      ADMIN_URL: preserve(),
      BOT_TOKEN: preserve(),
      BOT_USERNAME: preserve(),
      CRYPTOBOT_API_TOKEN: preserve(),
      CRYPTOBOT_NETWORK: preserve(),
      CRYPTOBOT_WEBHOOK_SECRET: preserve(),
      DATABASE_URL: preserve(),
      ENCRYPTION_KEY: preserve(),
      JWT_SECRET: preserve(),
      LANDING_URL: preserve(),
      LOG_LEVEL: preserve(),
      MINIAPP_URL: preserve(),
      NEXT_PUBLIC_API_URL: preserve(),
      NEXT_PUBLIC_BOT_USERNAME: preserve(),
      PORT: preserve(),
      PRICE_ORACLE_URL: preserve(),
      RAILWAY_DOCKERFILE_PATH: preserve(),
      REDIS_URL: preserve(),
      SERVICE_TOKEN: preserve(),
      SESSION_SECRET: preserve(),
      STARS_USD_RATE: preserve(),
      TRONGRID_API_KEY: preserve(),
      TRON_HOT_WALLET_KEY: preserve(),
      TRON_MASTER_XPUB: preserve(),
      TRON_MIN_CONFIRMATIONS: preserve(),
      TRON_NETWORK: preserve(),
      TRON_SWEEP_THRESHOLD: preserve(),
      TRON_SWEEP_TO_ADDRESS: preserve(),
      TRON_USDT_CONTRACT: preserve(),
      WEBHOOK_SECRET: preserve(),
      WEBHOOK_URL: preserve(),
    },
  });
  const bot = service("bot", {
    source: tgshop,
    replicas: { "sfo": 1 },
    build: { watchPatterns: ["apps/bot/**", "packages/**", "package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "tsconfig.base.json"] },
    healthcheck: "/health",
    healthcheckTimeout: 120,
    env: {
      ADMIN_IDS: preserve(),
      ADMIN_MINIAPP_URL: preserve(),
      ADMIN_URL: preserve(),
      BOT_TOKEN: preserve(),
      BOT_USERNAME: preserve(),
      CRYPTOBOT_API_TOKEN: preserve(),
      CRYPTOBOT_NETWORK: preserve(),
      CRYPTOBOT_WEBHOOK_SECRET: preserve(),
      DATABASE_URL: preserve(),
      ENCRYPTION_KEY: preserve(),
      JWT_SECRET: preserve(),
      LANDING_URL: preserve(),
      LOG_LEVEL: preserve(),
      MINIAPP_URL: preserve(),
      NEXT_PUBLIC_API_URL: preserve(),
      NEXT_PUBLIC_BOT_USERNAME: preserve(),
      PORT: preserve(),
      PRICE_ORACLE_URL: preserve(),
      RAILWAY_DOCKERFILE_PATH: preserve(),
      REDIS_URL: preserve(),
      SERVICE_TOKEN: preserve(),
      SESSION_SECRET: preserve(),
      STARS_USD_RATE: preserve(),
      TRONGRID_API_KEY: preserve(),
      TRON_HOT_WALLET_KEY: preserve(),
      TRON_MASTER_XPUB: preserve(),
      TRON_MIN_CONFIRMATIONS: preserve(),
      TRON_NETWORK: preserve(),
      TRON_SWEEP_THRESHOLD: preserve(),
      TRON_SWEEP_TO_ADDRESS: preserve(),
      TRON_USDT_CONTRACT: preserve(),
      WEBHOOK_SECRET: preserve(),
      WEBHOOK_URL: preserve(),
    },
  });
  const adminMiniapp = service("admin-miniapp", {
    source: tgshop,
    replicas: { "sfo": 1 },
    build: { watchPatterns: ["apps/admin-miniapp/**", "packages/**", "package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "tsconfig.base.json"] },
    healthcheck: "/",
    healthcheckTimeout: 120,
    env: {
      ADMIN_IDS: preserve(),
      ADMIN_MINIAPP_URL: preserve(),
      ADMIN_URL: preserve(),
      BOT_TOKEN: preserve(),
      BOT_USERNAME: preserve(),
      CRYPTOBOT_API_TOKEN: preserve(),
      CRYPTOBOT_NETWORK: preserve(),
      CRYPTOBOT_WEBHOOK_SECRET: preserve(),
      DATABASE_URL: preserve(),
      ENCRYPTION_KEY: preserve(),
      JWT_SECRET: preserve(),
      LANDING_URL: preserve(),
      LOG_LEVEL: preserve(),
      MINIAPP_URL: preserve(),
      NEXT_PUBLIC_API_URL: preserve(),
      NEXT_PUBLIC_BOT_USERNAME: preserve(),
      PORT: preserve(),
      PRICE_ORACLE_URL: preserve(),
      RAILWAY_DOCKERFILE_PATH: preserve(),
      REDIS_URL: preserve(),
      SERVICE_TOKEN: preserve(),
      SESSION_SECRET: preserve(),
      STARS_USD_RATE: preserve(),
      TRONGRID_API_KEY: preserve(),
      TRON_HOT_WALLET_KEY: preserve(),
      TRON_MASTER_XPUB: preserve(),
      TRON_MIN_CONFIRMATIONS: preserve(),
      TRON_NETWORK: preserve(),
      TRON_SWEEP_THRESHOLD: preserve(),
      TRON_SWEEP_TO_ADDRESS: preserve(),
      TRON_USDT_CONTRACT: preserve(),
      WEBHOOK_SECRET: preserve(),
      WEBHOOK_URL: preserve(),
    },
  });
  const miniapp = service("miniapp", {
    source: tgshop,
    replicas: { "sfo": 1 },
    build: { watchPatterns: ["apps/miniapp/**", "packages/**", "package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "tsconfig.base.json"] },
    healthcheck: "/",
    healthcheckTimeout: 120,
    env: {
      ADMIN_IDS: preserve(),
      ADMIN_MINIAPP_URL: preserve(),
      ADMIN_URL: preserve(),
      BOT_TOKEN: preserve(),
      BOT_USERNAME: preserve(),
      CRYPTOBOT_API_TOKEN: preserve(),
      CRYPTOBOT_NETWORK: preserve(),
      CRYPTOBOT_WEBHOOK_SECRET: preserve(),
      DATABASE_URL: preserve(),
      ENCRYPTION_KEY: preserve(),
      JWT_SECRET: preserve(),
      LANDING_URL: preserve(),
      LOG_LEVEL: preserve(),
      MINIAPP_URL: preserve(),
      NEXT_PUBLIC_API_URL: preserve(),
      NEXT_PUBLIC_BOT_USERNAME: preserve(),
      PORT: preserve(),
      PRICE_ORACLE_URL: preserve(),
      RAILWAY_DOCKERFILE_PATH: preserve(),
      REDIS_URL: preserve(),
      SERVICE_TOKEN: preserve(),
      SESSION_SECRET: preserve(),
      STARS_USD_RATE: preserve(),
      TRONGRID_API_KEY: preserve(),
      TRON_HOT_WALLET_KEY: preserve(),
      TRON_MASTER_XPUB: preserve(),
      TRON_MIN_CONFIRMATIONS: preserve(),
      TRON_NETWORK: preserve(),
      TRON_SWEEP_THRESHOLD: preserve(),
      TRON_SWEEP_TO_ADDRESS: preserve(),
      TRON_USDT_CONTRACT: preserve(),
      WEBHOOK_SECRET: preserve(),
      WEBHOOK_URL: preserve(),
    },
  });
  const admin = service("admin", {
    source: tgshop,
    replicas: { "sfo": 1 },
    build: { watchPatterns: ["apps/admin/**", "packages/**", "package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "tsconfig.base.json"] },
    // "/" answers 307 → /login; healthchecks need a 200, so probe /login.
    healthcheck: "/login",
    healthcheckTimeout: 120,
    env: {
      ADMIN_IDS: preserve(),
      ADMIN_MINIAPP_URL: preserve(),
      ADMIN_URL: preserve(),
      BOT_TOKEN: preserve(),
      BOT_USERNAME: preserve(),
      CRYPTOBOT_API_TOKEN: preserve(),
      CRYPTOBOT_NETWORK: preserve(),
      CRYPTOBOT_WEBHOOK_SECRET: preserve(),
      DATABASE_URL: preserve(),
      ENCRYPTION_KEY: preserve(),
      JWT_SECRET: preserve(),
      LANDING_URL: preserve(),
      LOG_LEVEL: preserve(),
      MINIAPP_URL: preserve(),
      NEXT_PUBLIC_API_URL: preserve(),
      NEXT_PUBLIC_BOT_USERNAME: preserve(),
      PORT: preserve(),
      PRICE_ORACLE_URL: preserve(),
      RAILWAY_DOCKERFILE_PATH: preserve(),
      REDIS_URL: preserve(),
      SERVICE_TOKEN: preserve(),
      SESSION_SECRET: preserve(),
      STARS_USD_RATE: preserve(),
      TRONGRID_API_KEY: preserve(),
      TRON_HOT_WALLET_KEY: preserve(),
      TRON_MASTER_XPUB: preserve(),
      TRON_MIN_CONFIRMATIONS: preserve(),
      TRON_NETWORK: preserve(),
      TRON_SWEEP_THRESHOLD: preserve(),
      TRON_SWEEP_TO_ADDRESS: preserve(),
      TRON_USDT_CONTRACT: preserve(),
      WEBHOOK_SECRET: preserve(),
      WEBHOOK_URL: preserve(),
    },
  });

  return project("tgshop", {
    resources: [Postgres, worker, landing, bot, adminMiniapp, Redis, miniapp, admin, redisVolume, postgresVolume],
  });
});
