#!/usr/bin/env bash
#
# gen-keys.sh — generates strong random values for ENCRYPTION_KEY, JWT_SECRET,
# WEBHOOK_SECRET, and SERVICE_TOKEN, printed as .env-ready lines.
#
# Usage:
#   ./scripts/gen-keys.sh                 # print to stdout
#   ./scripts/gen-keys.sh >> .env         # append to your .env (review before committing!)
#
# ENCRYPTION_KEY is emitted as a 64-char hex string (32 raw bytes), matching
# the format accepted by @tgshop/core's loadEncryptionKey() (64-char hex OR
# base64 decoding to exactly 32 bytes). Do NOT regenerate ENCRYPTION_KEY on an
# existing deployment — any StockItem.payloadEnc / Order.deliveredPayloadEnc
# rows encrypted under the old key become permanently undecryptable.
set -euo pipefail

gen_hex32() {
  openssl rand -hex 32
}

gen_base64_32() {
  openssl rand -base64 32
}

cat <<EOF
# Generated by scripts/gen-keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# WARNING: ENCRYPTION_KEY is irreversible once data is encrypted under it.
# Back it up somewhere safe outside of source control.
ENCRYPTION_KEY=$(gen_hex32)
JWT_SECRET=$(gen_base64_32)
# Signs the admin panel's session cookie. The admin app requires >= 32 chars.
SESSION_SECRET=$(gen_base64_32)
WEBHOOK_SECRET=$(gen_base64_32)
SERVICE_TOKEN=$(gen_base64_32)
EOF
